allow-lan: true
bind-address: '*'
dns:
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  enable: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fallback-filter:
    geoip: false
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
  ipv6: true
  listen: 0.0.0.0:53
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
external-controller: 127.0.0.1:9090
mode: global
port: 7890
proxies:
- cipher: chacha20-ietf-poly1305
  name: ss
  password: bf2022bf
  port: 443
  server: 23.106.152.193
  type: ss
  udp: true
proxy-groups:
- name: PROXY
  proxies:
  - ss
  type: select
socks-port: 7891
